linters:
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - err113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - revive
    - mnd
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - testpackage
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl

linters-settings:
  govet:
    shadow: true
  golint:
    min-confidence: 0
  wsl:
    allow-cuddle-declarations: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/becoded/go-harvest)
  goimports:
    local-prefixes: github.com/becoded/go-harvest
  depguard:
    rules:
      Main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/becoded/go-harvest
          - github.com/google/go-querystring
          - github.com/sirupsen/logrus
      Test:
        files:
          - $test
        allow:
          - $gostd
          - github.com/becoded/go-harvest
          - github.com/google/go-querystring
          - github.com/stretchr/testify
issues:
  exclude:
    - 'shadow: declaration of "err" shadows declaration at line'
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - bodyclose
        - dupl
        - goerr113
    - linters:
        - lll
      source: "^//go:generate "
